version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8030"
    environment:
      PORT: 8030
      env: debug
  db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080