name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gofmtの実行
        run: gofmt -l -w -s .
      - name: APIサーバーのビルド
        run: go build -v .
      # 単体テストを実行
      - name: 単体テスト実行
        run: go test -v .