name: Go build and test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gofmtの実行
        run: gofmt -l -w -s .
      - name: APIサーバーのビルド
        run: go build -v .
      # 単体テストを実行
      - name: 単体テスト実行
        run: go test -v .
  deploy_docker_image_to_aws:
    name: Deploy docker image to AWS
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: configure AWS credentials to deploy to aws resources
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.OIDC_PROVIDER}}:role/github_actions_deploy
          aws-region: ${{ secrets.AWS_REGION}}
      - name: authorize docker to push to ECR
        run: aws ecr get-login-password --region $aws-region | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.$aws-region.amazonaws.com
      # docker imageをbuild
      # secretsの情報をbuild時に渡す
      - name: build docker image
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          SEVER_PORT: 8030
          ENV: "release"
        run: docker image build --build-arg MYSQL_DATABASE=$MYSQL_DATABASE --build-arg MYSQL_USER=$MYSQL_USER --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD --build-arg DB_ENDPOINT=$DB_ENDPOINT --build-arg ENV=release --build-arg SEVER_PORT=$SEVER_PORT -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$aws-region.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest .
      # docker imageをECRにpush
      - name: push docker image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$aws-region.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest
